### ISSUE TITLE
Fullscreen support doesn't work properly on retina

### ISSUE THREAD

**Issue by Arcnor** [Arcnor/pixel-dungeon-gdx#11]
There is a bug on LWJGL 2.9.1. We need 2.9.2 that has a fix, but it hasn't been released on Maven yet. More info on http://lwjgl.org/forum/index.php/topic,5329.0.html and https://github.com/libgdx/libgdx/issues/1623

**Comment by watabou** [comment]
It's a bad bug, because after switching to full screen there is now way to switch back (the settings buttons in unreachable). Can we test for retina and disable the checkbox?

**Comment by Arcnor** [comment]
We might be able to detect it using `Display.getPixelScaleFactor()`, although I need to check if a flag is necessary (http://lwjgl.org/wiki/index.php?title=Using_High_DPI_Mode).

Another thing we can do is using our own version of LWJGL and LibGDX for now (I compiled a version without those problems) but this is a bit of a pain

**Comment by Arcnor** [comment]
Actually, assigning to you, I don't have a retina screen to test this on until the weekend, so it will be better if you can do the testing :)
