### ISSUE TITLE
Add proper versions

### ISSUE THREAD

**Issue by Arcnor** [Arcnor/pixel-dungeon-gdx#16]
Right now, the version that shows on the main screen is "???". Also, every platform has a different version on their metadata information.

**Comment by watabou** [comment]
I see "???" on desktop and Android (though I'm pretty sure that it was "1.7.1c" at some point).

**Comment by Arcnor** [comment]
I'll have to test it again, but for Desktop, the version will only show
when you generate a JAR with `gradlew dist`. For Android, I think it should
always work.

But I'll try it :)

**Comment by Arcnor** [comment]
Tested again, Android, iOS and Desktop (when running the JAR generated by `desktop:dist`) show the correct version. If it doesn't work on Android for you, can you check if there is an exception or something like that?
