### ISSUE TITLE
"Halo" effect looks like non-filled circle

### ISSUE THREAD

**Issue by watabou** [Arcnor/pixel-dungeon-gdx#20]

**Comment by Arcnor** [comment]
I don't understand which halo is looking bad? The one in the "About" screen looks exactly as it does in the last Android version, so I'm sure I'm missing something :D.

**Comment by watabou** [comment]
That's "flare" effect, not "halo" :))) 
"Halo" effect should look like a filled translucent circle, it is used when the hero gets "illuminated" (when using a torch for example).
I think drawCircle should be replaced by fillCircle somewhere there...

**Comment by Arcnor** [comment]
I see. Well, the Halo uses drawCircle instead of fillCircle, yes.

I can fix this one if you're not actively working on it. If you are, just assign the issue to yourself, or assign it to me in any other case :)
