### ISSUE TITLE
Save files encryption

### ISSUE THREAD

**Issue by watabou** [Arcnor/pixel-dungeon-gdx#25]
Currently game progress is saved in JSON, so saved games are very easy to edit in text editor. On mobile it's less a problem, because the files are harder to access, but on desktop we need some lightweight encryption (nothing serious, just to make these files human unreadable).

**Comment by prurigro** [comment]
What about writing the JSON saved games in **binary** rather than **ASCII** as a simple measure to make cheating more work? I feel like anyone able to edit the config at that point would also be capable of finding the key/password and using it to decrypt/encrypt the save.

**Comment by Arcnor** [comment]
Well, I don't think the idea is to avoid at all costs people cheating. Just to deter the lazy ones, I guess.

I was thinking about doing a simple XOR, or maybe something a bit more involved with symmetric encryption and a key stored somewhere in the JAR.

**Comment by prurigro** [comment]
@Arcnor: I've recently found myself transferring my save data between my laptop and phone, depending on what's more convenient to use at the time. If you have different keys for different builds, this might make doing that more difficult? Obviously this isn't a common use case, but I figured it'd be worth mentioning in case you'd wanted to consider it.

**Comment by danielkerr** [comment]
you have actually  made the game to hard. i think editing the json is the only way to advance
