### ISSUE TITLE
Controls reset to default after loading

### ISSUE THREAD

**Issue by prurigro** [Arcnor/pixel-dungeon-gdx#36]
I can change the controls and have them work great for the duration of session (great job btw!), and I'll see their new values in **pd-prefs** after exiting, but when I start the game back up they'll have reverted to their original values, and the default values are in **pd-prefs** after I exiting again.

I haven't had a chance to look at the code to see what the issue might be yet, so I'll add that my system is an up to date _x86_64_ **Arch Linux** box using the **jre8-openjdk** runtime (in case that changes anything.)

Cheers!

**Comment by Arcnor** [comment]
Yeah, I took a quick look at the code, and we seem to be resetting the controls before loading them, so they are always the default ones. I'll let @watabou take this one.
