### ISSUE TITLE
Ability to change key bindings during the game

### ISSUE THREAD

**Issue by watabou** [Arcnor/pixel-dungeon-gdx#49]
There is no reason to prevent user from changing key bindings without exiting to the main menu.

**Comment by prurigro** [comment]
I haven't looked closely to see, but is there a reason to prevent toggling fullscreen and windowed modes from in game as well?

**Comment by watabou** [comment]
@prurigro Actually, yes, there is, though it's more relevant to the original Android version. When toggling these modes, the app window gets resized and the current game scene is restarted (the same happens when you resize the window by dragging its frame for example). Many things happen in the process and one of the most annoying is playing the gong sound. Probably it can be fixed.
